"""Asset universe for the financial signal system."""

from __future__ import annotations

from typing import Dict, List

ASSETS: List[Dict[str, str]] = [
    # Metals
    {"symbol": "GC=F", "name": "Gold", "category": "Metals"},
    {"symbol": "SI=F", "name": "Silver", "category": "Metals"},
    {"symbol": "PL=F", "name": "Platinum", "category": "Metals"},
    {"symbol": "PA=F", "name": "Palladium", "category": "Metals"},
    {"symbol": "HG=F", "name": "Copper", "category": "Metals"},

    # Energy
    {"symbol": "BZ=F", "name": "Brent Oil", "category": "Energy"},
    {"symbol": "CL=F", "name": "WTI Oil", "category": "Energy"},
    {"symbol": "NG=F", "name": "Natural Gas", "category": "Energy"},
    {"symbol": "RB=F", "name": "RBOB Gasoline", "category": "Energy"},
    {"symbol": "HO=F", "name": "Heating Oil", "category": "Energy"},

    # Indices
    {"symbol": "^GSPC", "name": "S&P 500", "category": "Index"},
    {"symbol": "^IXIC", "name": "Nasdaq Composite", "category": "Index"},
    {"symbol": "^DJI", "name": "Dow Jones", "category": "Index"},
    {"symbol": "^RUT", "name": "Russell 2000", "category": "Index"},
    {"symbol": "^VIX", "name": "CBOE Volatility Index", "category": "Index"},
    {"symbol": "^GDAXI", "name": "DAX", "category": "Index"},
    {"symbol": "^FTSE", "name": "FTSE 100", "category": "Index"},
    {"symbol": "^N225", "name": "Nikkei 225", "category": "Index"},
    {"symbol": "^BVSP", "name": "Bovespa", "category": "Index"},
    {"symbol": "^HSI", "name": "Hang Seng", "category": "Index"},
    {"symbol": "000001.SS", "name": "Shanghai Composite", "category": "Index"},
    {"symbol": "^STOXX50E", "name": "Euro Stoxx 50", "category": "Index"},

    # Crypto
    {"symbol": "BTC-USD", "name": "Bitcoin", "category": "Crypto"},
    {"symbol": "ETH-USD", "name": "Ethereum", "category": "Crypto"},
    {"symbol": "BNB-USD", "name": "BNB", "category": "Crypto"},
    {"symbol": "SOL-USD", "name": "Solana", "category": "Crypto"},
    {"symbol": "XRP-USD", "name": "XRP", "category": "Crypto"},
    {"symbol": "ADA-USD", "name": "Cardano", "category": "Crypto"},
    {"symbol": "DOGE-USD", "name": "Dogecoin", "category": "Crypto"},
    {"symbol": "AVAX-USD", "name": "Avalanche", "category": "Crypto"},
    {"symbol": "DOT-USD", "name": "Polkadot", "category": "Crypto"},
    {"symbol": "MATIC-USD", "name": "Polygon", "category": "Crypto"},
    {"symbol": "LINK-USD", "name": "Chainlink", "category": "Crypto"},
    {"symbol": "LTC-USD", "name": "Litecoin", "category": "Crypto"},

    # ETFs
    {"symbol": "SPY", "name": "SPDR S&P 500 ETF", "category": "ETF"},
    {"symbol": "QQQ", "name": "Invesco QQQ ETF", "category": "ETF"},
    {"symbol": "IWM", "name": "iShares Russell 2000 ETF", "category": "ETF"},
    {"symbol": "DIA", "name": "SPDR Dow Jones ETF", "category": "ETF"},
    {"symbol": "GLD", "name": "SPDR Gold Shares", "category": "ETF"},
    {"symbol": "SLV", "name": "iShares Silver Trust", "category": "ETF"},
    {"symbol": "USO", "name": "United States Oil Fund", "category": "ETF"},
    {"symbol": "UNG", "name": "United States Natural Gas Fund", "category": "ETF"},
    {"symbol": "TLT", "name": "20+ Year Treasury ETF", "category": "ETF"},
    {"symbol": "XLE", "name": "Energy Select Sector SPDR", "category": "ETF"},
    {"symbol": "XLF", "name": "Financial Select Sector SPDR", "category": "ETF"},
    {"symbol": "XLK", "name": "Technology Select Sector SPDR", "category": "ETF"},
    {"symbol": "XLV", "name": "Health Care Select Sector SPDR", "category": "ETF"},
    {"symbol": "XLI", "name": "Industrial Select Sector SPDR", "category": "ETF"},
    {"symbol": "XLY", "name": "Consumer Discretionary SPDR", "category": "ETF"},
    {"symbol": "XLP", "name": "Consumer Staples SPDR", "category": "ETF"},
    {"symbol": "EEM", "name": "iShares MSCI Emerging Markets", "category": "ETF"},
    {"symbol": "EFA", "name": "iShares MSCI EAFE", "category": "ETF"},
    {"symbol": "ARKK", "name": "ARK Innovation ETF", "category": "ETF"},
    {"symbol": "VNQ", "name": "Vanguard Real Estate ETF", "category": "ETF"},

    # US large-cap stocks
    {"symbol": "AAPL", "name": "Apple", "category": "Stock"},
    {"symbol": "MSFT", "name": "Microsoft", "category": "Stock"},
    {"symbol": "GOOGL", "name": "Alphabet", "category": "Stock"},
    {"symbol": "AMZN", "name": "Amazon", "category": "Stock"},
    {"symbol": "NVDA", "name": "NVIDIA", "category": "Stock"},
    {"symbol": "TSLA", "name": "Tesla", "category": "Stock"},
    {"symbol": "META", "name": "Meta Platforms", "category": "Stock"},
    {"symbol": "NFLX", "name": "Netflix", "category": "Stock"},
    {"symbol": "AMD", "name": "AMD", "category": "Stock"},
    {"symbol": "INTC", "name": "Intel", "category": "Stock"},
    {"symbol": "CRM", "name": "Salesforce", "category": "Stock"},
    {"symbol": "ORCL", "name": "Oracle", "category": "Stock"},
    {"symbol": "ADBE", "name": "Adobe", "category": "Stock"},
    {"symbol": "CSCO", "name": "Cisco", "category": "Stock"},
    {"symbol": "QCOM", "name": "Qualcomm", "category": "Stock"},
    {"symbol": "AVGO", "name": "Broadcom", "category": "Stock"},
    {"symbol": "JPM", "name": "JPMorgan Chase", "category": "Stock"},
    {"symbol": "BAC", "name": "Bank of America", "category": "Stock"},
    {"symbol": "WFC", "name": "Wells Fargo", "category": "Stock"},
    {"symbol": "GS", "name": "Goldman Sachs", "category": "Stock"},
    {"symbol": "MS", "name": "Morgan Stanley", "category": "Stock"},
    {"symbol": "BRK-B", "name": "Berkshire Hathaway B", "category": "Stock"},
    {"symbol": "V", "name": "Visa", "category": "Stock"},
    {"symbol": "MA", "name": "Mastercard", "category": "Stock"},
    {"symbol": "PYPL", "name": "PayPal", "category": "Stock"},
    {"symbol": "XOM", "name": "Exxon Mobil", "category": "Stock"},
    {"symbol": "CVX", "name": "Chevron", "category": "Stock"},
    {"symbol": "COP", "name": "ConocoPhillips", "category": "Stock"},
    {"symbol": "SHEL", "name": "Shell", "category": "Stock"},
    {"symbol": "BP", "name": "BP", "category": "Stock"},
    {"symbol": "JNJ", "name": "Johnson & Johnson", "category": "Stock"},
    {"symbol": "PFE", "name": "Pfizer", "category": "Stock"},
    {"symbol": "MRK", "name": "Merck", "category": "Stock"},
    {"symbol": "ABT", "name": "Abbott", "category": "Stock"},
    {"symbol": "UNH", "name": "UnitedHealth", "category": "Stock"},
    {"symbol": "WMT", "name": "Walmart", "category": "Stock"},
    {"symbol": "COST", "name": "Costco", "category": "Stock"},
    {"symbol": "HD", "name": "Home Depot", "category": "Stock"},
    {"symbol": "MCD", "name": "McDonald's", "category": "Stock"},
    {"symbol": "NKE", "name": "Nike", "category": "Stock"},
    {"symbol": "KO", "name": "Coca-Cola", "category": "Stock"},
    {"symbol": "PEP", "name": "PepsiCo", "category": "Stock"},
    {"symbol": "PG", "name": "Procter & Gamble", "category": "Stock"},
    {"symbol": "DIS", "name": "Walt Disney", "category": "Stock"},
    {"symbol": "BABA", "name": "Alibaba", "category": "Stock"},
    {"symbol": "TSM", "name": "TSMC", "category": "Stock"},
    {"symbol": "ASML", "name": "ASML", "category": "Stock"},
    {"symbol": "SONY", "name": "Sony", "category": "Stock"},
    {"symbol": "TM", "name": "Toyota", "category": "Stock"},
    {"symbol": "RACE", "name": "Ferrari", "category": "Stock"},
    {"symbol": "UBER", "name": "Uber", "category": "Stock"},
    {"symbol": "SHOP", "name": "Shopify", "category": "Stock"},
    {"symbol": "SQ", "name": "Block", "category": "Stock"},
    {"symbol": "COIN", "name": "Coinbase", "category": "Stock"},
]


def sanitize_symbol(symbol: str) -> str:
    """Make ticker safe for filesystem path."""
    return symbol.replace("=", "_").replace("^", "_").replace("-", "_").replace("/", "_")
